[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate --schema prisma/schema.prisma",
  "npm run build:web"
]

[start]
cmd = "bash scripts/start-web.sh"
